version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env

  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  mlflow:
    image: ghcr.io/mlflow/mlflow
    command: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db
    ports:
      - "5000:5000"

volumes:
  mongo_data:


