name: Deploy to Azure GPU VM
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_REGISTRY }}
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY }}/object-detection:latest .
          docker push ${{ secrets.AZURE_REGISTRY }}/object-detection:latest
      - name: Deploy to Azure VM
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            # Check if Docker is installed
            if ! command -v docker &> /dev/null
            then
              echo "Docker is not installed. Please install Docker by following the instructions at https://docs.docker.com/engine/install/"
              exit 1
            fi

            az vm run-command invoke \
              -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
              -n ${{ secrets.AZURE_VM_NAME }} \
              --command-id RunShellScript \
              --scripts "docker pull ${{ secrets.AZURE_REGISTRY }}/object-detection:latest && docker run -d --gpus all ${{ secrets.AZURE_REGISTRY }}/object-detection:latest"
